name: Test Build GameHandler
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build venv
        run: python3 -m venv .build_venv

      - name: Install PyInstaller
        run: .build_venv/bin/pip install --quiet pyinstaller

      - name: Install GameHandler dependencies
        run: .build_venv/bin/pip install --quiet -r binaries/AscendaraGameHandler/requirements.txt

      - name: Compile AscendaraGameHandler
        run: |
          mkdir -p binaries/AscendaraGameHandler/dist
          .build_venv/bin/python3 -m PyInstaller \
            --onefile \
            --noconfirm \
            --name AscendaraGameHandler \
            --distpath binaries/AscendaraGameHandler/dist \
            --workpath binaries/AscendaraGameHandler/dist/build_tmp \
            --specpath binaries/AscendaraGameHandler/dist/spec_tmp \
            binaries/AscendaraGameHandler/src/AscendaraGameHandler.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AscendaraGameHandler-ubuntu-latest
          path: binaries/AscendaraGameHandler/dist/AscendaraGameHandler
